name: set_version

name: My Workflow
on: [push, pull_request]
jobs:
  build:
  runs-on: ubuntu-latest
  run: |
    sed  -r "s/^(\s*BUILD\s*=\s*'[0-9]+.)([0-9]+)(.*)$/\1$(TZ=UTC date +%y%m%d-%H%M)\3/g" beast-feeder.py
